version: '3.1'

services:
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: "$DATABASE_ROOT_PASSWORD"
      MARIADB_USER: "$DATABASE_USER"
      MARIADB_PASSWORD: "$DATABASE_PASSWORD"
    volumes:
      - /var/log/mysql:/var/lib/mysql
      #- ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: "./backend"
    depends_on: 
      - "database"
    labels:
      - "traefik.http.routers.admin.rule=PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.entryPoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=80"
      - "traefik.http.routers.admin.service=admin"
    restart: always
    volumes:
    - ./.env:./.env
    networks:
      - traefik-net

networks:
  traefik-net:
      external:
        name: traefik-net