version: '3.1'

services:
  backend:
    build: "./backend"
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entryPoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
      - "traefik.http.routers.backend.service=front"
    restart: unless-stopped
    networks:
      - traefik-net

networks:
  traefik-net:
      external:
        name: traefik-net