version: '3.1'

services:
  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    networks:
      - admn-net
    environment:
      MARIADB_ROOT_PASSWORD: "$DATABASE_ROOT_PASSWORD"
      MARIADB_USER: "$DATABASE_USER"
      MARIADB_PASSWORD: "$DATABASE_PASSWORD"
    volumes:
      - /var/log/mysql:/var/lib/mysql

  backend:
    build: "./backend"
    depends_on: 
      - "database"
    labels:
      - "traefik.http.routers.admin.rule=PathPrefix(`/admin`)"
      - "traefik.http.routers.admin.entryPoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=80"
      - "traefik.http.routers.admin.service=admin"
    restart: always
    volumes:
    - .env:/usr/src/backend/.env
    networks:
      - traefik-net
      - admn-net

  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - database
    environment:
      DB_TYPE: mariadb
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: "$DATABASE_USER"
      DB_PASS: "$DATABASE_PASSWORD"
      DB_NAME: wiki
    restart: unless-stopped
    labels:
      - "traefik.http.routers.wiki.rule=PathPrefix(`/wiki`)"
      - "traefik.http.routers.wiki.entryPoints=web"
      - "traefik.http.services.wiki.loadbalancer.server.port=3000"
      - "traefik.http.routers.wiki.service=wiki"
    networks:
      - traefik-net
      - admn-net

networks:
  admn-net:
    driver: bridge
  traefik-net:
      external:
        name: traefik-net
